В этом блоке проанализируем А/Б тест

Мы добавили на лендинг с оформлением дебетовой карты (https://www.tinkoff.ru/cards/debit-cards/tinkoff-black/) информацию о дополнительных кэшбеках, которые появляются благодаря нашим патнерам. Рассчитываем, что это вырастит конверсию из переходов на лендинг в оформление дебетовой карты. 

В приложенном файле вам доступны логи переходов на сайт и последующего оформления карточки за каждый день.

In [2]:
# загрузим необходимые пакеты

import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats

In [3]:
# Загрузите таблицу в датафрейм

df = pd.read_csv('hw_ab.csv')

In [4]:
# Посмотрите на поля и проанализируйте таблицу: она содержит поля 
# date — дата захода пользователя на лендинг
# id — идентификатор, присвоенный пользователю
# group — группа теста или контроля
# converted – 1, если пользователь оформил карточку и 0, если не оформил

In [5]:
df

             date       id    group  converted
0      2023-08-01  5030836  control          0
1      2023-08-01  5091425  control          0
2      2023-08-01  5106537  control          0
3      2023-08-01  4556522  control          0
4      2023-08-01  4002917  control          0
...           ...      ...      ...        ...
94773  2023-11-01  7729860     test          0
94774  2023-11-01  8088716     test          0
94775  2023-11-01  4478281     test          0
94776  2023-11-01  5710762     test          0
94777  2023-11-01  8505333     test          0

[94778 rows x 4 columns]

In [6]:
df.info(),df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94778 entries, 0 to 94777
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       94778 non-null  object
 1   id         94778 non-null  int64
 2   group      94778 non-null  object
 3   converted  94778 non-null  int64
dtypes: int64(2), object(2)
memory usage: 2.9+ MB

(None,
          date       id    group  converted
 0  2023-08-01  5030836  control          0
 1  2023-08-01  5091425  control          0
 2  2023-08-01  5106537  control          0
 3  2023-08-01  4556522  control          0
 4  2023-08-01  4002917  control          0)

In [7]:
# убедитесь,что пользователи уникальные

In [9]:
unique_users = df['id'].nunique()
unique_users

94778

In [10]:
len(df)==df['id'].nunique()

True

In [8]:
# убедитесь, что пользователей в тесте и контроле приблизительно равное количество, 
# в каждой группе каждый день теста были пользователи, и они как оформляли карту, так и нет

In [9]:
group_couts = df['group'].value_counts()
group_couts

group
test       47448
control    47330
Name: count, dtype: int64

In [10]:
valid_days = df.groupby(['date', 'group'])['converted'].agg(
    has_conv = lambda  x:(x==1).any(),
    has_not_conv = lambda x: (x==0).any()
).reset_index()

valid_days

           date    group  has_conv  has_not_conv
0    2023-08-01  control      True          True
1    2023-08-01     test      True          True
2    2023-08-02  control      True          True
3    2023-08-02     test      True          True
4    2023-08-03  control      True          True
..          ...      ...       ...           ...
181  2023-10-30     test      True          True
182  2023-10-31  control      True          True
183  2023-10-31     test      True          True
184  2023-11-01  control      True          True
185  2023-11-01     test      True          True

[186 rows x 4 columns]

In [11]:
df.groupby('group').nunique()

         date     id  converted
group
control    93  47330          2
test       93  47448          2

In [11]:
# Флаги наличия хотябы одного конвентирванного и неконв
invalid_days = valid_days[~(valid_days['has_conv']&valid_days['has_not_conv'])]
invalid_days

Empty DataFrame
Columns: [date, group, has_conv, has_not_conv]
Index: []

In [12]:
# отличаются ли конверсии в тесте и в контроле?
df[['group','converted','id']].groupby(['group','converted']).count()

                      id
group   converted
control 0          42408
        1           4922
test    0          41774
        1           5674

In [14]:
# считаем конверсию в контроле исходя из таблицы

4922/(4922+42408)

0.10399323896049018

In [15]:
# конферсия в тесте
5674/(5674+41774)

0.11958354409037261

In [16]:
# отношение конверсий
conv_test = sum(list(df.loc[df['group']=='test']['converted']))
seen_test = len(list(df.loc[df['group']=='test']['converted']))

conv_control = sum(list(df.loc[df['group']=='control']['converted']))
seen_control = len(list(df.loc[df['group']=='control']['converted']))


((conv_test/seen_test)/(conv_control/seen_control)-1)

0.14991652616768292

In [28]:
test['converted'].info()

<class 'pandas.core.series.Series'>
Index: 47448 entries, 512 to 94777
Series name: converted
Non-Null Count  Dtype
--------------  -----
47448 non-null  int64
dtypes: int64(1)
memory usage: 741.4 KB

In [38]:
# посчитайте число открытых карт в контроле
cout_control = (control['converted']).sum()
cout_control

np.int64(4922)

In [39]:
seen_c = df[df['group']=='control']
seen_control = seen_c.shape[0]
seen_control

47330

In [43]:
((count_test/seen_test)/(cout_control/seen_control)-1)*100

np.float64(14.991652616768292)